onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - sharp
  - unrs-resolver

ignoredBuiltDependencies:
  - esbuild

allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  esbuild: false
  sharp: true
  unrs-resolver: true
